### ISSUE TITLE
Codext no longer fills page in Firefox 94 

### ISSUE THREAD

**Issue by Roysten** [bbc/codext#10]
Starting from Firefox 94 codext no longer fills the page:
![image](https://user-images.githubusercontent.com/1564539/141735812-9fd705e3-5325-4f03-9a03-9c1d6803cf56.png)

It seems that Firefox requires that all elements have the height and width specified as 100%, all the way from the html tag to the codext iframe. Unfortunately this does add a scrollbar to the page, so I can imagine that this is not the ideal solution.

**Comment by PyvesB** [comment]
Hello @Roysten ! 👋🏻 

Thanks for reporting this.

> Unfortunately this does add a scrollbar to the page, so I can imagine that this is not the ideal solution.

Could you please share a screenshot of how it looks?

**Comment by Roysten** [comment]
I was going to send a screenshot, but I found here https://stackoverflow.com/questions/9129182/iframe-100-height-causes-vertical-scrollbar that the scrollbar can be prevented by setting display: block.

The following HTML fixes the issue in Firefox 94 for me:

```html
<html style="height: 100%;">
    <body style="margin: 0px; height: 100%;">
        <iframe style="border: 0px none; width: 100%; height: 100%; display: block;"></iframe>
    </body>
</html>
```

**Comment by PyvesB** [comment]
Awesome, thanks for looking into this! Would you like to submit a pull request?

**Comment by danielthepope** [comment]
Thanks for raising the PR (#11). That's now merged, so I'll close this issue. We'll get the new version released to browsers very soon!

**Comment by PyvesB** [comment]
The new version is available on Firefox, and will soon be available on Chrome as well. 😉
