### ISSUE TITLE
Please add the ability to view Github raw files

### ISSUE THREAD

**Issue by smac89** [bbc/codext#14]
Is there a reason for not supporting github? I couldn't find where in your code github is restricted, but for some reason this extension doesn't work for Github raw files

**Comment by PyvesB** [comment]
Hello 👋🏻 

This limitation is documented [in the readme](https://github.com/bbc/codext#known-issues). Feel free to upvote the linked bugs on the Firefox and Chrome issue trackers. 😉

**Comment by smac89** [comment]
That's unfortunate :frowning_face: 

Thanks for the update. Guess we'll just have to sit tight and wait...
