### ISSUE TITLE
Add a dark theme?

### ISSUE THREAD

**Issue by h0adp0re** [bbc/codext#9]
Any chance for a dark theme? Sometimes it's pretty hard on the eyes, especially when it's already dark out and/or everything else has dark mode applied.

**Comment by PyvesB** [comment]
Hello @h0adp0re ! 👋🏻 

There already is a dark theme, @jbhurruth contributed that in  #8. Does it not work for you?

**Comment by h0adp0re** [comment]
Hey! I can't see any other themes other than high contrast. I'm on Firefox, Codext 1.1.1.

**Comment by PyvesB** [comment]
That's odd, I'm using Firefox as well with Codext 1.1.1, and the `Dark Theme` menu does appear as expected when right clicking on the extension's logo in the address bar:
<img width="213" alt="Screenshot 2021-06-07 at 15 27 30" src="https://user-images.githubusercontent.com/10694593/121034739-289f6c80-c7a5-11eb-842b-a1bb3523ae9e.png">

**Comment by h0adp0re** [comment]
Ah, sorry. I thought this was available from the command palette. Didn't know this icon is interactive. All sorted now, thanks!

**Comment by PyvesB** [comment]
If you think mentioning this in the README would be useful, feel free to send a pull request. 😉

**Comment by h0adp0re** [comment]
I would but I'm afraid I'd botch the phrasing and placement of it. Writing other people's readmes isn't one of my strong suits.
